### PR TITLE
use curl

### PR DESCRIPTION
**Pull request by toooni**

### CODE REVIEW

**Comment by dmzoneill** [comment]
Why did you close this?

**Comment by jaggedsoft** [comment]
I'm wondering the same thing. Since it was closed right away, I didn't ever see it
Happy to make the switch for version `v0.1.0`

**Comment by dmzoneill** [comment]
I wasn't sure if you were partial to the file_get_contents, would prefer curl also.

I'll send a patch tomorrow maybe 😊

**Comment by jaggedsoft** [comment]
Nope, it's nice because it doesn't need an extra dependency, but we're using composer so that shouldn't matter. I'm planning on a complete rework of this library once I have time. It can be made to be much easier.

**Comment by jaggedsoft** [comment]
Thanks!

**Pull request closed without merging**
