### PR TITLE
Add withdrawFee() by eugypalu

### PR DESCRIPTION
**Pull request by eugypalu**

### CODE REVIEW

**Comment by dmzoneill** [comment]
thanks for the commit.  1 or 2 small things

are we able to type hint those arguments?
it might be confusing for your index to be $timestamp... $timestamp inside '' wont be substituted.

i might be confused by the code, my apologies if i have interpreted it wrong. 

```
public function withdrawFee( string $asset, int $timestamp, $recvWindow = null) {
```

should this 
```
 $params = ["wapi"=>true, "asset"=>$asset, $timestamp];
```
be
```
 $params = ["wapi"=>true, "asset"=>$asset,  "timestamp" => $timestamp];
```

should this 
```
$params['$timestamp'] = $timestamp;
```
be 
```
$params['timestamp'] = $timestamp;
```

**Comment by eugypalu** [comment]
1 
$recvWindow is LONG

Your changes of points 2 and 3 are correct

2
`$params = ["wapi"=>true, "asset"=>$asset,  "timestamp" => $timestamp];` 

3
`$params['timestamp'] = $timestamp;
`

**Comment by jaggedsoft** [comment]
Thank you for your contribution

**Comment by jaggedsoft** [comment]
Thanks again, sorry it took so long

Added in https://github.com/jaggedsoft/php-binance-api/commit/44d8026cd9dfd1cf2b1a9d6dba8fdbeeea71d7e6
Available in `v0.2.8`

**Pull request closed without merging**
