### PR TITLE
add php-binance-api-rate-limiter.php && Round as necessary before selling

### PR DESCRIPTION
**Pull request by max-grim**
1. Laravel return error Class 'Binance\RateLimiter' not found
2. Round as necessary before selling

### CODE REVIEW

**Comment by jaggedsoft** [comment]
thank you

**Comment by max-grim** [comment]
@jaggedsoft please update https://packagist.org/packages/jaggedsoft/php-binance-api )

**Comment by jaggedsoft** [comment]
It should be set to v0.5.9, packagist just downloads the latest release
https://github.com/jaggedsoft/php-binance-api/releases

**Comment by max-grim** [comment]
@jaggedsoft I don’t understand how it all works) When does it get 0.5.9?

**Comment by jaggedsoft** [comment]
hmm I am not sure why it's not updating

**Comment by max-grim** [comment]
@jaggedsoft Did you make a WebHook?

There are some webhooks to be added to your repository server, see https://packagist.org/about#how-to-update-packages for them - this will update the list of package versions immediately on pushing or tagging. Otherwise, updates are only performed once a week

https://stackoverflow.com/questions/48617182/packagist-does-not-take-tags-releases-that-i-push

**Comment by jaggedsoft** [comment]
thanks, looks like I needed to update the webhook

**Pull request merged**
