### PR TITLE
Create asset.php

### PR DESCRIPTION
**Pull request by afsharsafavi**
this is example for assetDetail method (#210)

### CODE REVIEW

**Comment by jaggedsoft** [comment]
Good work friend, thank you for your contributions!

**Comment by afsharsafavi** [comment]
Hi @jaggedsoft , you merged my third commit without merging my second commit for "php-binance-api.php"
I wrote assetDetail method in my second commit.
Now in master branch we have example without it's method.
https://github.com/afsharsafavi/php-binance-api/commit/8dc159470b7f5c71bad55cc33df8e2e2351cc847

**Comment by jaggedsoft** [comment]
I don't see any other active pull requests

**Comment by jaggedsoft** [comment]
I'll copy that function over manually, thanks

**Review by mohammedsoud — APPROVED** [review]

**Pull request merged**
