### PR TITLE
Implemented numberOfDecimals()

### PR DESCRIPTION
**Pull request by areebmajeed**
I've added the missing function.

### CODE REVIEW

**Comment by jaggedsoft** [comment]
Thank you!

**Comment by max-grim** [comment]
Thank you, sorry to forget to add a function (

One moment, the function only works correctly with the string type

**Comment by max-grim** [comment]
@areebmajeed

**Comment by areebmajeed** [comment]
> Thank you, sorry to forget to add a function (
> 
> One moment, the function only works correctly with the string type

Are you sure? I just tested it: http://sandbox.onlinephpfunctions.com/code/770de34d8f9f01a24744adacac775d84f1c91e6e

**Comment by max-grim** [comment]
> > Thank you, sorry to forget to add a function (
> > One moment, the function only works correctly with the string type
> 
> Are you sure? I just tested it: http://sandbox.onlinephpfunctions.com/code/770de34d8f9f01a24744adacac775d84f1c91e6e

http://sandbox.onlinephpfunctions.com/code/cf43efe6f7c794e7dc7b6c353019adcd815da581

**Comment by areebmajeed** [comment]
You're right. I'll be having a look and I will fix this.

**Pull request merged**
